apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: potnt
  name: potnt-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - potnt.kuly.cloud
      secretName: potnt-frontend-tls
  rules:
    - host: potnt.kuly.cloud
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: potnt-backend
                port:
                  number: 8000
