apiVersion: v1
kind: Service
metadata:
  namespace: potnt
  name: potnt-backend
  labels:
    app: potnt-backend
    tier: backend
spec:
  ports:
    - port: 8000
  selector:
    app: potnt-backend
    tier: backend
